# NumPy Basics: Arrays and Vectorized Computation

In [4]:
import numpy as np

In [4]:
my_np_array = np.arange(1000000)

In [5]:
my_py_list = list(range(1000000))

In [7]:
%time for _ in range(10): my_np_arr2 = my_np_array * 2

Wall time: 25.9 ms


In [8]:
%time for _ in range(10): my_py_list2 = my_py_list * 2

Wall time: 247 ms


In [9]:
data = np.random.randn(2,3)

In [10]:
data

array([[-1.08952246,  0.21799987,  1.50171522],
       [ 0.84756221,  0.46713782, -0.32806169]])

In [12]:
data * 10

array([[-10.8952246 ,   2.17999872,  15.0171522 ],
       [  8.47562205,   4.67137823,  -3.28061693]])

In [14]:
data + data

array([[-2.17904492,  0.43599974,  3.00343044],
       [ 1.69512441,  0.93427565, -0.65612339]])

In [16]:
data.shape

(2, 3)

In [17]:
data.dtype

dtype('float64')

In [1]:
data = list(range(10))

In [2]:
data

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
arr1 = np.array(data)

In [6]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [1]:
data2 = [[1,2,4,5,7],[10,20, 40, 50, 60]]

In [6]:
arr2 = np.array(data2)

In [7]:
arr2

array([[ 1,  2,  4,  5,  7],
       [10, 20, 40, 50, 60]])

In [8]:
arr2.ndim

2

In [10]:
arr2.shape

(2, 5)

In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.zeros(10).dtype

dtype('float64')

In [14]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
arr3 = np.zeros((2,3))

In [19]:
arr3.shape

(2, 3)

In [20]:
arr1 = np.array([1,2,3], dtype = np.int16)

In [21]:
arr1

array([1, 2, 3], dtype=int16)

In [22]:
arr1.dtype

dtype('int16')

In [23]:
arr1.ndim

1

In [24]:
arr1.shape

(3,)

In [25]:
arr = np.array([1, 2, 3, 4, 5])

In [26]:
arr_flot = arr.astype(np.float16)

In [27]:
arr_flot

array([1., 2., 3., 4., 5.], dtype=float16)

In [28]:
arr1 = np.array([1,2,3,4,5,6])

In [29]:
arr1[5]

6

In [30]:
arr1[3:5] = 12

In [31]:
arr1

array([ 1,  2,  3, 12, 12,  6])

In [36]:
arr2 = arr1[:3]

In [37]:
arr2

array([1, 2, 3])

In [38]:
arr2[2] = 11

In [39]:
arr1

array([ 1,  2, 11, 12, 12,  6])