# NumPy Basics: Arrays and Vectorized Computation

In [3]:
import numpy as np

In [4]:
my_np_array = np.arange(1000000)

In [5]:
my_py_list = list(range(1000000))

In [7]:
%time for _ in range(10): my_np_arr2 = my_np_array * 2

Wall time: 25.9 ms


In [8]:
%time for _ in range(10): my_py_list2 = my_py_list * 2

Wall time: 247 ms


In [9]:
data = np.random.randn(2,3)

In [10]:
data

array([[-1.08952246,  0.21799987,  1.50171522],
       [ 0.84756221,  0.46713782, -0.32806169]])

In [12]:
data * 10

array([[-10.8952246 ,   2.17999872,  15.0171522 ],
       [  8.47562205,   4.67137823,  -3.28061693]])

In [14]:
data + data

array([[-2.17904492,  0.43599974,  3.00343044],
       [ 1.69512441,  0.93427565, -0.65612339]])

In [16]:
data.shape

(2, 3)

In [17]:
data.dtype

dtype('float64')

In [18]:
data = list(range(10))

In [19]:
data

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [20]:
arr1 = np.array(data)

In [21]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
data2 = []